# Generated by Django 4.2.7 on 2025-06-04 23:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('batch_name', models.CharField(max_length=50)),
                ('batch_type', models.CharField(choices=[('layers', 'Layers'), ('broilers', 'Broilers'), ('mixed', 'Mixed')], max_length=10)),
                ('initial_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('current_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date_acquired', models.DateField()),
                ('acquisition_cost_per_bird', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_laying_start', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chicken_batches', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Chicken Batch',
                'verbose_name_plural': 'Chicken Batches',
                'db_table': 'livestock_chicken_batches',
                'ordering': ['-date_acquired'],
                'unique_together': {('farm', 'batch_name')},
            },
        ),
        migrations.CreateModel(
            name='ChickenReduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.CharField(choices=[('death', 'Death/Disease'), ('sale', 'Sale'), ('consumption', 'Consumption'), ('transfer', 'Transfer'), ('other', 'Other')], max_length=15)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reductions', to='livestock.chickenbatch')),
            ],
            options={
                'verbose_name': 'Chicken Reduction',
                'verbose_name_plural': 'Chicken Reductions',
                'db_table': 'livestock_chicken_reductions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('tag_number', models.CharField(max_length=20, unique=True)),
                ('breed', models.CharField(choices=[('friesian', 'Friesian'), ('jersey', 'Jersey'), ('ayrshire', 'Ayrshire'), ('guernsey', 'Guernsey'), ('holstein', 'Holstein'), ('crossbreed', 'Crossbreed'), ('indigenous', 'Indigenous')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_acquired', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_stage', models.CharField(choices=[('calf', 'Calf'), ('heifer', 'Heifer'), ('lactating', 'Lactating'), ('dry', 'Dry Period'), ('pregnant', 'Pregnant'), ('heat', 'In Heat'), ('sick', 'Sick'), ('sold', 'Sold')], default='heifer', max_length=15)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('father_info', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cow_images/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cows', to='farms.farm')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calves', to='livestock.cow')),
            ],
            options={
                'verbose_name': 'Cow',
                'verbose_name_plural': 'Cows',
                'db_table': 'livestock_cows',
                'ordering': ['name'],
                'unique_together': {('farm', 'tag_number')},
            },
        ),
    ]
